### ISSUE TITLE
想和作者沟通一下

### ISSUE THREAD

**Issue by ZhangMingZhao1** [fantasticit/sailkit#2]
[think](https://github.com/fantasticit/think) think这个项目， readme里面说基于yjs的备份和恢复这块 
>基于 yjs 的版本备份和恢复（部分同学提出增量保存 diff，个人还是建议全量 snapshot）

这个snapshot你指的是全量对象存储还是yjs现在snapshot概念

目前也在研究yjs协同这块，是否可以加个微信交流一下

**Comment by fantasticit** [comment]
参考： https://github.com/yjs/yjs-demos/tree/main/prosemirror-versions
微信和github 同名。

**Comment by ZhangMingZhao1** [comment]
@fantasticit 这个demo看过，仍然有一些问题：
1. 这个例子没有持久化的部分
2. 这个例子只是用snapshot在前端做对比预览，不是严格意义的版本恢复，而且作者在文档里说不建议用snapshot做恢复，又没说原因：
![image](https://github.com/fantasticit/sailkit/assets/29058747/70ec1806-89f8-4f11-89bf-ab84a9e16d3b)

**Comment by fantasticit** [comment]
snapshot 做比对，encode 一下做存储，需要对 y-prosemirror 的代码做些修改。
版本恢复用 json content。
